sudo: required
language: minimal

git:
  depth: 2

branches:
  only:
  - master
  - devel

services:
  - docker

env:
  global:
    - IMAGE_REPO=gcr.io/dd-decaf-cfbf6/metanetx
    - IMAGE_TAG=${TRAVIS_BRANCH}

install:
  - docker build -t ${IMAGE_REPO}:${TRAVIS_COMMIT::12} -t ${IMAGE_REPO}:${TRAVIS_BRANCH} .
  - make setup

script:
  - make black-check
  - make flake8
  - make isort-check
  - make license
  - make safety
  - # Run the tests and report coverage (see https://docs.codecov.io/docs/testing-with-docker).
  - mkdir --parents /tmp/coverage
  - docker-compose run --rm -e ENVIRONMENT=testing -v "/tmp/coverage:/tmp/coverage" web pytest --cov-report "xml:/tmp/coverage/coverage.xml" --cov-report term --cov=src/metanetx
  - bash <(curl -s https://codecov.io/bash) -f "/tmp/coverage/coverage.xml"

before_deploy:
  - ./scripts/install_gcloud.sh
  - ./scripts/install_kubectl.sh
  - docker push ${IMAGE_REPO}:${TRAVIS_COMMIT::12}
  - docker push ${IMAGE_REPO}:${TRAVIS_BRANCH}

deploy:
  provider: script
  script: ./scripts/deploy.sh
  on:
    all_branches: true

notifications:
  email: false
  slack:
    rooms:
      - <GENERATE SECURE TOKEN>
    on_success: change
    on_failure: change
    on_pull_requests: false
